Repository Yuerino/cub3d, pull requests merged in 2022-05, with the labels that each got.

#6 fix: texture sliding
  includes/rendering.h
  srcs/rendering/cast_rays.c
Labels: bug

#8 feat: map validator and rendering
  Makefile
  cub3d.c
  includes/controls.h
  includes/cub3d.h
  includes/input_handler.h
  includes/rendering.h
  includes/utils.h
  maps/basic.cub
  maps/test.cub
  srcs/controls.c
  srcs/input_handler/free.c
  srcs/input_handler/init.c
  srcs/input_handler/read.c
  srcs/input_handler/read_map.c
  srcs/input_handler/read_texture.c
  srcs/input_handler/validate_map.c
  srcs/mouse_controls.c
  srcs/rendering/cast_rays.c
  srcs/rendering/minimap.c
  srcs/rendering/putimg.c
  utils/color.c
  utils/image.c
  utils/is_ext_valid.c
  utils/put_pixel.c
Labels: enhancement, mandatory

#9 Fix: Put include line in the input handler, changed the initial player pos…
  includes/input_handler.h
  srcs/input_handler/read_map.c
Labels: enhancement
